#define IMPLEMENT
#include "function.h"
#include "primitive.h"

#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

// The type name must be one word.
// Therefore, the type alias `ASCIIZ` is used here instead of `char *`.
typedef char* ASCIIZ;

// Defines all Fn(...) types.
use_recursive_Fn(size_t, char, ASCIIZ);
// The above `use_recursive_Fn(size_t, char, ASCIIZ)` is shorthand
// notation of the following:
// ~~~c
// // Define `Fn(char, ASCIIZ)` function object type,
// // that takes `char` and returns `ASCIIZ`.
// use_Fn(char, ASCIIZ);
// // Define `Fn(size_t, char, ASCIIZ)` function object type,
// // that takes `size_t` and returns `Fn(char, ASCIIZ)`.
// use_Fn(size_t, char, ASCIIZ);
// ~~~

// Prototype declaration of the constructor `repeat`.
Fn(size_t, char, ASCIIZ) repeat(void);

// Definition of the constructor `repeat()` and function body of the
// function object returned from `repeat()`.
//
// Note that the constructor code is automatically generated by `fn()`
// macro.
//
// In the function body, arguments passed to the function object can be
// accessed by `args` pointer. In this case, `args` is a pointer to a
// tuple-like structure such as `struct { size_t _0; char _1; }` in this
// example.
fn(repeat, size_t, char, ASCIIZ) {
  size_t len = args->_0; // 1st argument
  char c = args->_1;     // 2nd argument
  ASCIIZ ret = calloc(len + 1, sizeof(char));
  if (ret) {
    memset(ret, c, len);
  }
  return ret;
}

int main(void) {
  Fn(size_t, char, ASCIIZ) f = repeat();
  Fn(char, ASCIIZ) g = fn_apply(f, 3);

  ASCIIZ s1 = fn_apply(g, 'A');
  assert(!strcmp("AAA", s1));
  printf("%s\n", s1); // --> "AAA"
  free(s1);

  ASCIIZ s2 = fn_apply(g, 'B');
  assert(!strcmp("BBB", s2));
  printf("%s\n", s2); // --> "BBB"
  free(s2);

  assert(f.args == g.args);

  ASCIIZ s3 = fn_apply(f, 2, 'C');
  assert(!strcmp("CC", s3));
  printf("%s\n", s3); // --> "CC"
  free(s3);

  ASCIIZ s4 = fn_apply(g, 'B');
  assert(!strcmp("BB", s4));
  printf("%s\n", s4); // --> "BB"
  free(s4);

  trait(Drop(Fn(char, ASCIIZ))).drop(&g);
  trait(Drop(Fn(size_t, char, ASCIIZ))).drop(&f);

  return 0;
}
